# https://docs.ros.org/en/eloquent/Tutorials/Run-2-nodes-in-two-separate-docker-containers.html
# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: "3"
services:
    robojames:
        stdin_open: true
        tty: true
        container_name: robojames
        image: robojames-jetson
        runtime: nvidia
        environment:
            - NVIDIA_VISIBLE_DEVICES=all
            - NVIDIA_DRIVER_CAPABILITIES=all
        devices:
            - /dev/ttyUSB0
            - /dev/ttyUSB1
            - /dev/bus/usb
            - $(readlink -f /dev/input/xbox-controller)
        #restart: unless-stopped
        network_mode: host
        pid: host
